char * stringlst = [
/* Palette: inkscape.gpl */NC_("Palette", "Black"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "90% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "80% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "70% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "60% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "50% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "40% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "30% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "20% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "10% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "7.5% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "5% Gray"),
/* Palette: inkscape.gpl *//* xgettext:no-c-format */NC_("Palette", "2.5% Gray"),
/* Palette: inkscape.gpl */NC_("Palette", "White"),
/* Palette: inkscape.gpl */NC_("Palette", "Maroon (#800000)"),
/* Palette: inkscape.gpl */NC_("Palette", "Red (#FF0000)"),
/* Palette: inkscape.gpl */NC_("Palette", "Olive (#808000)"),
/* Palette: inkscape.gpl */NC_("Palette", "Yellow (#FFFF00)"),
/* Palette: inkscape.gpl */NC_("Palette", "Green (#008000)"),
/* Palette: inkscape.gpl */NC_("Palette", "Lime (#00FF00)"),
/* Palette: inkscape.gpl */NC_("Palette", "Teal (#008080)"),
/* Palette: inkscape.gpl */NC_("Palette", "Aqua (#00FFFF)"),
/* Palette: inkscape.gpl */NC_("Palette", "Navy (#000080)"),
/* Palette: inkscape.gpl */NC_("Palette", "Blue (#0000FF)"),
/* Palette: inkscape.gpl */NC_("Palette", "Purple (#800080)"),
/* Palette: inkscape.gpl */NC_("Palette", "Fuchsia (#FF00FF)"),
/* Palette: svg.gpl */NC_("Palette", "black (#000000)"),
/* Palette: svg.gpl */NC_("Palette", "dimgray (#696969)"),
/* Palette: svg.gpl */NC_("Palette", "gray (#808080)"),
/* Palette: svg.gpl */NC_("Palette", "darkgray (#A9A9A9)"),
/* Palette: svg.gpl */NC_("Palette", "silver (#C0C0C0)"),
/* Palette: svg.gpl */NC_("Palette", "lightgray (#D3D3D3)"),
/* Palette: svg.gpl */NC_("Palette", "gainsboro (#DCDCDC)"),
/* Palette: svg.gpl */NC_("Palette", "whitesmoke (#F5F5F5)"),
/* Palette: svg.gpl */NC_("Palette", "white (#FFFFFF)"),
/* Palette: svg.gpl */NC_("Palette", "rosybrown (#BC8F8F)"),
/* Palette: svg.gpl */NC_("Palette", "indianred (#CD5C5C)"),
/* Palette: svg.gpl */NC_("Palette", "brown (#A52A2A)"),
/* Palette: svg.gpl */NC_("Palette", "firebrick (#B22222)"),
/* Palette: svg.gpl */NC_("Palette", "lightcoral (#F08080)"),
/* Palette: svg.gpl */NC_("Palette", "maroon (#800000)"),
/* Palette: svg.gpl */NC_("Palette", "darkred (#8B0000)"),
/* Palette: svg.gpl */NC_("Palette", "red (#FF0000)"),
/* Palette: svg.gpl */NC_("Palette", "snow (#FFFAFA)"),
/* Palette: svg.gpl */NC_("Palette", "mistyrose (#FFE4E1)"),
/* Palette: svg.gpl */NC_("Palette", "salmon (#FA8072)"),
/* Palette: svg.gpl */NC_("Palette", "tomato (#FF6347)"),
/* Palette: svg.gpl */NC_("Palette", "darksalmon (#E9967A)"),
/* Palette: svg.gpl */NC_("Palette", "coral (#FF7F50)"),
/* Palette: svg.gpl */NC_("Palette", "orangered (#FF4500)"),
/* Palette: svg.gpl */NC_("Palette", "lightsalmon (#FFA07A)"),
/* Palette: svg.gpl */NC_("Palette", "sienna (#A0522D)"),
/* Palette: svg.gpl */NC_("Palette", "seashell (#FFF5EE)"),
/* Palette: svg.gpl */NC_("Palette", "chocolate (#D2691E)"),
/* Palette: svg.gpl */NC_("Palette", "saddlebrown (#8B4513)"),
/* Palette: svg.gpl */NC_("Palette", "sandybrown (#F4A460)"),
/* Palette: svg.gpl */NC_("Palette", "peachpuff (#FFDAB9)"),
/* Palette: svg.gpl */NC_("Palette", "peru (#CD853F)"),
/* Palette: svg.gpl */NC_("Palette", "linen (#FAF0E6)"),
/* Palette: svg.gpl */NC_("Palette", "bisque (#FFE4C4)"),
/* Palette: svg.gpl */NC_("Palette", "darkorange (#FF8C00)"),
/* Palette: svg.gpl */NC_("Palette", "burlywood (#DEB887)"),
/* Palette: svg.gpl */NC_("Palette", "tan (#D2B48C)"),
/* Palette: svg.gpl */NC_("Palette", "antiquewhite (#FAEBD7)"),
/* Palette: svg.gpl */NC_("Palette", "navajowhite (#FFDEAD)"),
/* Palette: svg.gpl */NC_("Palette", "blanchedalmond (#FFEBCD)"),
/* Palette: svg.gpl */NC_("Palette", "papayawhip (#FFEFD5)"),
/* Palette: svg.gpl */NC_("Palette", "moccasin (#FFE4B5)"),
/* Palette: svg.gpl */NC_("Palette", "orange (#FFA500)"),
/* Palette: svg.gpl */NC_("Palette", "wheat (#F5DEB3)"),
/* Palette: svg.gpl */NC_("Palette", "oldlace (#FDF5E6)"),
/* Palette: svg.gpl */NC_("Palette", "floralwhite (#FFFAF0)"),
/* Palette: svg.gpl */NC_("Palette", "darkgoldenrod (#B8860B)"),
/* Palette: svg.gpl */NC_("Palette", "goldenrod (#DAA520)"),
/* Palette: svg.gpl */NC_("Palette", "cornsilk (#FFF8DC)"),
/* Palette: svg.gpl */NC_("Palette", "gold (#FFD700)"),
/* Palette: svg.gpl */NC_("Palette", "khaki (#F0E68C)"),
/* Palette: svg.gpl */NC_("Palette", "lemonchiffon (#FFFACD)"),
/* Palette: svg.gpl */NC_("Palette", "palegoldenrod (#EEE8AA)"),
/* Palette: svg.gpl */NC_("Palette", "darkkhaki (#BDB76B)"),
/* Palette: svg.gpl */NC_("Palette", "beige (#F5F5DC)"),
/* Palette: svg.gpl */NC_("Palette", "lightgoldenrodyellow (#FAFAD2)"),
/* Palette: svg.gpl */NC_("Palette", "olive (#808000)"),
/* Palette: svg.gpl */NC_("Palette", "yellow (#FFFF00)"),
/* Palette: svg.gpl */NC_("Palette", "lightyellow (#FFFFE0)"),
/* Palette: svg.gpl */NC_("Palette", "ivory (#FFFFF0)"),
/* Palette: svg.gpl */NC_("Palette", "olivedrab (#6B8E23)"),
/* Palette: svg.gpl */NC_("Palette", "yellowgreen (#9ACD32)"),
/* Palette: svg.gpl */NC_("Palette", "darkolivegreen (#556B2F)"),
/* Palette: svg.gpl */NC_("Palette", "greenyellow (#ADFF2F)"),
/* Palette: svg.gpl */NC_("Palette", "chartreuse (#7FFF00)"),
/* Palette: svg.gpl */NC_("Palette", "lawngreen (#7CFC00)"),
/* Palette: svg.gpl */NC_("Palette", "darkseagreen (#8FBC8F)"),
/* Palette: svg.gpl */NC_("Palette", "forestgreen (#228B22)"),
/* Palette: svg.gpl */NC_("Palette", "limegreen (#32CD32)"),
/* Palette: svg.gpl */NC_("Palette", "lightgreen (#90EE90)"),
/* Palette: svg.gpl */NC_("Palette", "palegreen (#98FB98)"),
/* Palette: svg.gpl */NC_("Palette", "darkgreen (#006400)"),
/* Palette: svg.gpl */NC_("Palette", "green (#008000)"),
/* Palette: svg.gpl */NC_("Palette", "lime (#00FF00)"),
/* Palette: svg.gpl */NC_("Palette", "honeydew (#F0FFF0)"),
/* Palette: svg.gpl */NC_("Palette", "seagreen (#2E8B57)"),
/* Palette: svg.gpl */NC_("Palette", "mediumseagreen (#3CB371)"),
/* Palette: svg.gpl */NC_("Palette", "springgreen (#00FF7F)"),
/* Palette: svg.gpl */NC_("Palette", "mintcream (#F5FFFA)"),
/* Palette: svg.gpl */NC_("Palette", "mediumspringgreen (#00FA9A)"),
/* Palette: svg.gpl */NC_("Palette", "mediumaquamarine (#66CDAA)"),
/* Palette: svg.gpl */NC_("Palette", "aquamarine (#7FFFD4)"),
/* Palette: svg.gpl */NC_("Palette", "turquoise (#40E0D0)"),
/* Palette: svg.gpl */NC_("Palette", "lightseagreen (#20B2AA)"),
/* Palette: svg.gpl */NC_("Palette", "mediumturquoise (#48D1CC)"),
/* Palette: svg.gpl */NC_("Palette", "darkslategray (#2F4F4F)"),
/* Palette: svg.gpl */NC_("Palette", "paleturquoise (#AFEEEE)"),
/* Palette: svg.gpl */NC_("Palette", "teal (#008080)"),
/* Palette: svg.gpl */NC_("Palette", "darkcyan (#008B8B)"),
/* Palette: svg.gpl */NC_("Palette", "cyan (#00FFFF)"),
/* Palette: svg.gpl */NC_("Palette", "lightcyan (#E0FFFF)"),
/* Palette: svg.gpl */NC_("Palette", "azure (#F0FFFF)"),
/* Palette: svg.gpl */NC_("Palette", "darkturquoise (#00CED1)"),
/* Palette: svg.gpl */NC_("Palette", "cadetblue (#5F9EA0)"),
/* Palette: svg.gpl */NC_("Palette", "powderblue (#B0E0E6)"),
/* Palette: svg.gpl */NC_("Palette", "lightblue (#ADD8E6)"),
/* Palette: svg.gpl */NC_("Palette", "deepskyblue (#00BFFF)"),
/* Palette: svg.gpl */NC_("Palette", "skyblue (#87CEEB)"),
/* Palette: svg.gpl */NC_("Palette", "lightskyblue (#87CEFA)"),
/* Palette: svg.gpl */NC_("Palette", "steelblue (#4682B4)"),
/* Palette: svg.gpl */NC_("Palette", "aliceblue (#F0F8FF)"),
/* Palette: svg.gpl */NC_("Palette", "dodgerblue (#1E90FF)"),
/* Palette: svg.gpl */NC_("Palette", "slategray (#708090)"),
/* Palette: svg.gpl */NC_("Palette", "lightslategray (#778899)"),
/* Palette: svg.gpl */NC_("Palette", "lightsteelblue (#B0C4DE)"),
/* Palette: svg.gpl */NC_("Palette", "cornflowerblue (#6495ED)"),
/* Palette: svg.gpl */NC_("Palette", "royalblue (#4169E1)"),
/* Palette: svg.gpl */NC_("Palette", "midnightblue (#191970)"),
/* Palette: svg.gpl */NC_("Palette", "lavender (#E6E6FA)"),
/* Palette: svg.gpl */NC_("Palette", "navy (#000080)"),
/* Palette: svg.gpl */NC_("Palette", "darkblue (#00008B)"),
/* Palette: svg.gpl */NC_("Palette", "mediumblue (#0000CD)"),
/* Palette: svg.gpl */NC_("Palette", "blue (#0000FF)"),
/* Palette: svg.gpl */NC_("Palette", "ghostwhite (#F8F8FF)"),
/* Palette: svg.gpl */NC_("Palette", "slateblue (#6A5ACD)"),
/* Palette: svg.gpl */NC_("Palette", "darkslateblue (#483D8B)"),
/* Palette: svg.gpl */NC_("Palette", "mediumslateblue (#7B68EE)"),
/* Palette: svg.gpl */NC_("Palette", "mediumpurple (#9370DB)"),
/* Palette: svg.gpl */NC_("Palette", "blueviolet (#8A2BE2)"),
/* Palette: svg.gpl */NC_("Palette", "indigo (#4B0082)"),
/* Palette: svg.gpl */NC_("Palette", "darkorchid (#9932CC)"),
/* Palette: svg.gpl */NC_("Palette", "darkviolet (#9400D3)"),
/* Palette: svg.gpl */NC_("Palette", "mediumorchid (#BA55D3)"),
/* Palette: svg.gpl */NC_("Palette", "thistle (#D8BFD8)"),
/* Palette: svg.gpl */NC_("Palette", "plum (#DDA0DD)"),
/* Palette: svg.gpl */NC_("Palette", "violet (#EE82EE)"),
/* Palette: svg.gpl */NC_("Palette", "purple (#800080)"),
/* Palette: svg.gpl */NC_("Palette", "darkmagenta (#8B008B)"),
/* Palette: svg.gpl */NC_("Palette", "magenta (#FF00FF)"),
/* Palette: svg.gpl */NC_("Palette", "orchid (#DA70D6)"),
/* Palette: svg.gpl */NC_("Palette", "mediumvioletred (#C71585)"),
/* Palette: svg.gpl */NC_("Palette", "deeppink (#FF1493)"),
/* Palette: svg.gpl */NC_("Palette", "hotpink (#FF69B4)"),
/* Palette: svg.gpl */NC_("Palette", "lavenderblush (#FFF0F5)"),
/* Palette: svg.gpl */NC_("Palette", "palevioletred (#DB7093)"),
/* Palette: svg.gpl */NC_("Palette", "crimson (#DC143C)"),
/* Palette: svg.gpl */NC_("Palette", "pink (#FFC0CB)"),
/* Palette: svg.gpl */NC_("Palette", "lightpink (#FFB6C1)"),
/* Palette: svg.gpl */NC_("Palette", "rebeccapurple (#663399)"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Butter 1"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Butter 2"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Butter 3"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Chameleon 1"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Chameleon 2"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Chameleon 3"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Orange 1"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Orange 2"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Orange 3"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Sky Blue 1"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Sky Blue 2"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Sky Blue 3"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Plum 1"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Plum 2"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Plum 3"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Chocolate 1"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Chocolate 2"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Chocolate 3"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Scarlet Red 1"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Scarlet Red 2"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Scarlet Red 3"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Snowy White"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Aluminium 1"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Aluminium 2"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Aluminium 3"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Aluminium 4"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Aluminium 5"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Aluminium 6"),
/* Palette: Tango-Palette.gpl */NC_("Palette", "Jet Black"),];