char * stringlst = [
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "AIGA Symbol Signs"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Telephone"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Telephone"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Mail"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Mail"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Currency Exchange"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Currency Exchange"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Currency Exchange - Euro"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Currency Exchange - Euro"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Cashier"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Cashier"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "First Aid"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "First Aid"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Lost and Found"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Lost and Found"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Coat Check"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Coat Check"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Baggage Lockers"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Baggage Lockers"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Escalator"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Escalator"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Escalator Down"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Escalator Down"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Escalator Up"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Escalator Up"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Stairs"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Stairs"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Stairs Down"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Stairs Down"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Stairs Up"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Stairs Up"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Elevator"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Elevator"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Toilets - Men"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Toilets - Men"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Toilets - Women"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Toilets - Women"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Toilets"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Toilets"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Nursery"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Nursery"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Drinking Fountain"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Drinking Fountain"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Waiting Room"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Waiting Room"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Information"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Information"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Hotel Information"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Hotel Information"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Air Transportation"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Air Transportation"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Heliport"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Heliport"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Taxi"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Taxi"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Bus"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Bus"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Ground Transportation"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Ground Transportation"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Rail Transportation"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Rail Transportation"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Water Transportation"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Water Transportation"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Car Rental"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Car Rental"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Restaurant"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Restaurant"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Coffeeshop"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Coffeeshop"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Bar"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Bar"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Shops"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Shops"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Barber Shop - Beauty Salon"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Barber Shop - Beauty Salon"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Barber Shop"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Barber Shop"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Beauty Salon"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Beauty Salon"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Ticket Purchase"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Ticket Purchase"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Baggage Check In"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Baggage Check In"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Baggage Claim"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Baggage Claim"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Customs"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Customs"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Immigration"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Immigration"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Departing Flights"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Departing Flights"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Arriving Flights"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Arriving Flights"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Smoking"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Smoking"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "No Smoking"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "No Smoking"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Parking"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Parking"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "No Parking"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "No Parking"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "No Dogs"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "No Dogs"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "No Entry"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "No Entry"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Exit"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Exit"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Fire Extinguisher"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Fire Extinguisher"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Right Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Right Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Forward and Right Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Forward and Right Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Up Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Up Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Forward and Left Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Forward and Left Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Left Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Left Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Left and Down Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Left and Down Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Down Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Down Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Right and Down Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "Right and Down Arrow"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "NPS Wheelchair Accessible - 1996"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "NPS Wheelchair Accessible - 1996"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "NPS Wheelchair Accessible"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "NPS Wheelchair Accessible"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "New Wheelchair Accessible"),
/* Symbols: AigaSymbols.svg */  NC_("Symbol", "New Wheelchair Accessible"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Word Balloons"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Thought Balloon"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Dream Speaking"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Rounded Balloon"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Squared Balloon"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Over the Phone"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Hip Balloon"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Circle Balloon"),
/* Symbols: BalloonSymbols.svg */  NC_("Symbol", "Exclaim Balloon"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Flow Chart Shapes"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Process"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Input/Output"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Document"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Manual Operation"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Preparation"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Merge"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Decision"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Magnetic Tape"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Display"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Auxiliary Operation"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Manual Input"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Extract"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Terminal/Interrupt"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Punched Card"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Punch Tape"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Online Storage"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Keying"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Sort"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Connector"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Off-Page Connector"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Transmittal Tape"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Communication Link"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Collate"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Comment/Annotation"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Core"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Predefined Process"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Magnetic Disk (Database)"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Magnetic Drum (Direct Access)"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Offline Storage"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Logical Or"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Logical And"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Delay"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Loop Limit Begin"),
/* Symbols: FlowSymbols.svg */  NC_("Symbol", "Loop Limit End"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Logic Symbols"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Xnor Gate"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Xor Gate"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Nor Gate"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Or Gate"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Nand Gate"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "And Gate"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Buffer"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Not Gate"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Buffer Small"),
/* Symbols: LogicSymbols.svg */  NC_("Symbol", "Not Gate Small"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "United States National Park Service Map Symbols"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Airport"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Airport"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Amphitheatre"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Amphitheatre"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Bicycle Trail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Bicycle Trail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Boat Launch"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Boat Launch"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Boat Tour"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Boat Tour"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Bus Stop"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Bus Stop"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Campfire"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Campfire"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Campground"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Campground"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "CanoeAccess"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "CanoeAccess"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Crosscountry Ski Trail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Crosscountry Ski Trail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Downhill Skiing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Downhill Skiing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Drinking Water"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Drinking Water"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "First Aid"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "First Aid"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Fishing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Fishing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Food Service"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Food Service"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Four Wheel Drive Road"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Four Wheel Drive Road"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Gas Station"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Gas Station"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Golfing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Golfing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Horseback Riding"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Horseback Riding"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Hospital"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Hospital"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Ice Skating"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Ice Skating"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Information"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Information"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Litter Receptacle"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Litter Receptacle"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Lodging"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Lodging"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Marina"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Marina"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Motorbike Trail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Motorbike Trail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Radiator Water"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Radiator Water"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Recycling"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Recycling"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Parking"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Parking"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Pets On Leash"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Pets On Leash"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Picnic Area"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Picnic Area"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Post Office"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Post Office"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Ranger Station"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Ranger Station"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "RV Campground"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "RV Campground"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Restrooms"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Restrooms"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Sailing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Sailing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Sanitary Disposal Station"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Sanitary Disposal Station"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Scuba Diving"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Scuba Diving"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Self Guided Trail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Self Guided Trail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Shelter"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Shelter"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Showers"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Showers"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Sledding"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Sledding"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "SnowmobileTrail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "SnowmobileTrail"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Stable"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Stable"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Store"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Store"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Swimming"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Swimming"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Telephone"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Telephone"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Emergency Telephone"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Emergency Telephone"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Trailhead"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Trailhead"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Wheelchair Accessible"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Wheelchair Accessible"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Wind Surfing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Wind Surfing"),
/* Symbols: MapSymbolsNPS.svg */  NC_("Symbol", "Blank"),];